version: 0.0
os: linux
files:
  - source: ./my-greeting-web-0.1.0.jar
    destination: /var/my-greeting-web/
  - source: ./my-greeting-web.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStop:
    - location: stopapp.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: startapp.sh
      timeout: 300
      runas: root

